### ISSUE TITLE
Po reštartu HA nedostupne dáta z PND

### ISSUE THREAD

**Issue by matomatusov** [ondrejvysek/HomeAssistant-CEZDistribuce-PND#9]
Bolo by možné aby po reštartu HA sa načitaly entity z PND? Musím ručne pustiť automatizáciu aby sa to znova načítalo.

**Comment by ondrejvysek** [comment]
Kouknu na možnosti. Díky tomu, že jsou senzory programově vytvářené, má limity. Jako dočasné řešení je další automatizace s trigerem startu HA a v příkladu níž je minutové čekání před spuštěním (ev se dá upravit stávající automatizace o další trigger)
```
- id: 'startup_delayed_action'
  alias: "Delayed Action After Startup"
  description: 'Performs an action one minute after Home Assistant starts.'
  trigger:
    - platform: homeassistant
      event: start
  action:
    - delay: '00:01:00'  # Delay for one minute
    - event: run_pnd
      event_data: {}
```

**Comment by matomatusov** [comment]
Myslel som, že by to mohlo byť aj súčasťou tej automatizace. Dik za informace. A Super projekt!!!
Možná ešte ten súbor pnd.py by sa mohol aktualizovať cez HACS.

**Comment by ondrejvysek** [comment]
ona ta upravená by mohla vypadat takto nějak:
```
alias: Run PND
description: ""
trigger:
  - platform: time
    at: "00:35:00"
  - platform: homeassistant
    event: start
condition: []
action:
  - delay:
      hours: 0
      minutes: 3
      seconds: 0
      milliseconds: 0
  - event: run_pnd
mode: single
```
nicméně ten delay ovlivní i ruční spuštění, vždy se na něj bude muset čekat. Také nevím (záleží na HW) jak dlouho startuje AppDaemon,... Asi bych spíš udělal druhou automatizaci a dal tam delay třeba 5 min. Zatím to do návodu nebudu dávat, uvidíme co se povede s těmi senzory.

ad HACS: ok, výzva přijata, pro verzi 2 nastuduji jak vytvořit HACS :) Spíš jsem potom laboroval s vlastním kontejnerem, aby nebylo závislé na AppDaemon
